/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) integrator_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};

/* integrator:(i0[3],i1[2])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000003e-002;
  a1=1.6666666666666666e-001;
  a2=arg[1] ? arg[1][0] : 0;
  a3=5.0000000000000000e-001;
  a4=arg[0] ? arg[0][2] : 0;
  a5=sin(a4);
  a5=(a3*a5);
  a6=arg[1] ? arg[1][1] : 0;
  a7=cos(a4);
  a7=(a6*a7);
  a8=sin(a4);
  a8=(a2*a8);
  a7=(a7-a8);
  a8=(a7/a3);
  a5=(a5*a8);
  a5=(a2+a5);
  a5=(a1*a5);
  a9=3.3333333333333331e-001;
  a7=(a0*a7);
  a7=(a4+a7);
  a10=sin(a7);
  a10=(a3*a10);
  a11=cos(a7);
  a11=(a6*a11);
  a12=sin(a7);
  a12=(a2*a12);
  a11=(a11-a12);
  a12=(a11/a3);
  a10=(a10*a12);
  a10=(a2+a10);
  a10=(a9*a10);
  a5=(a5+a10);
  a11=(a0*a11);
  a11=(a4+a11);
  a10=sin(a11);
  a10=(a3*a10);
  a13=cos(a11);
  a13=(a6*a13);
  a14=sin(a11);
  a14=(a2*a14);
  a13=(a13-a14);
  a13=(a13/a3);
  a10=(a10*a13);
  a10=(a2+a10);
  a10=(a9*a10);
  a5=(a5+a10);
  a10=(a0*a13);
  a10=(a4+a10);
  a14=sin(a10);
  a14=(a3*a14);
  a15=cos(a10);
  a15=(a6*a15);
  a16=sin(a10);
  a16=(a2*a16);
  a15=(a15-a16);
  a15=(a15/a3);
  a14=(a14*a15);
  a2=(a2+a14);
  a2=(a1*a2);
  a5=(a5+a2);
  a5=(a0*a5);
  a2=arg[0] ? arg[0][0] : 0;
  a5=(a5+a2);
  if (res[0]!=0) res[0][0]=a5;
  a5=cos(a4);
  a5=(a3*a5);
  a5=(a5*a8);
  a5=(a6-a5);
  a5=(a1*a5);
  a7=cos(a7);
  a7=(a3*a7);
  a7=(a7*a12);
  a7=(a6-a7);
  a7=(a9*a7);
  a5=(a5+a7);
  a11=cos(a11);
  a11=(a3*a11);
  a11=(a11*a13);
  a11=(a6-a11);
  a11=(a9*a11);
  a5=(a5+a11);
  a10=cos(a10);
  a3=(a3*a10);
  a3=(a3*a15);
  a6=(a6-a3);
  a6=(a1*a6);
  a5=(a5+a6);
  a5=(a0*a5);
  a6=arg[0] ? arg[0][1] : 0;
  a5=(a5+a6);
  if (res[0]!=0) res[0][1]=a5;
  a8=(a1*a8);
  a12=(a9*a12);
  a8=(a8+a12);
  a9=(a9*a13);
  a8=(a8+a9);
  a1=(a1*a15);
  a8=(a8+a1);
  a0=(a0*a8);
  a0=(a0+a4);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

int integrator(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

void integrator_incref(void) {
}

void integrator_decref(void) {
}

casadi_int integrator_n_in(void) { return 2;}

casadi_int integrator_n_out(void) { return 1;}

const char* integrator_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* integrator_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* integrator_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* integrator_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

int integrator_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
